openapi: 3.0.0
info:
  title: Voice API
  version: 1.0.0
  description: API for managing agents and calls

paths:
  /agent:
    post:
      summary: Create or update an agent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Agent'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agent'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    get:
      summary: Get an agent by ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agent'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Agent not found
        '500':
          description: Internal server error

    delete:
      summary: Delete an agent by ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Agent not found
        '500':
          description: Internal server error

  /agents:
    get:
      summary: List agents
      parameters:
        - name: cursor
          in: query
          required: false
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentList'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /call:
    post:
      summary: Create a call
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCallRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Call'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    get:
      summary: Get a call by ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Call'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Call not found
        '500':
          description: Internal server error

  /call/context:
    post:
      summary: Set call context
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetCallContextRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Call'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Call not found
        '500':
          description: Internal server error

  /calls:
    get:
      summary: List calls
      parameters:
        - name: cursor
          in: query
          required: false
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
        - name: agent_id
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallList'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

components:
  schemas:
    Agent:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        phone_number:
          type: string
        system_prompt:
          type: string
        initial_message:
          type: string
        llm_model:
          type: string
          enum: [gpt-4o, flyflow-voice]
        voice_id:
          type: string
        webhook:
          type: string
        tools:
          type: array
          items:
            $ref: '#/components/schemas/Tool'
        filler_words:
          type: boolean
        filler_words_whitelist:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - system_prompt

    Tool:
      type: object
      properties:
        type:
          type: string
          enum: [function]
        function:
          $ref: '#/components/schemas/ToolFunction'
      required:
        - type
        - function

    ToolFunction:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        parameters:
          type: object
      required:
        - name
        - description
        - parameters

    AgentList:
      type: object
      properties:
        num_items:
          type: integer
        cursor:
          type: string
        agents:
          type: array
          items:
            $ref: '#/components/schemas/Agent'

    CreateCallRequest:
      type: object
      properties:
        from:
          type: string
        to:
          type: string
        context:
          type: string
      required:
        - from
        - to

    Call:
      type: object
      properties:
        id:
          type: string
        agent_id:
          type: string
        from:
          type: string
        to:
          type: string
        context:
          type: string
        status:
          type: string
        created_at:
          type: string
          format: date-time
        ended_at:
          type: string
          format: date-time
        duration:
          type: integer
        transcript:
          type: array
          items:
            $ref: '#/components/schemas/CallMessage'

    CallMessage:
      type: object
      properties:
        speaker:
          type: string
          enum: [agent, user]
        text:
          type: string

    SetCallContextRequest:
      type: object
      properties:
        id:
          type: string
        context:
          type: string
      required:
        - id
        - context

    CallList:
      type: object
      properties:
        num_items:
          type: integer
        cursor:
          type: string
        calls:
          type: array
          items:
            $ref: '#/components/schemas/Call'
